# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
workflows:

    jobs:
      - build:
        docker:
          - image: circleci/node:13.8.0
          steps:
            - checkout
            - run npm i
            - run npm run lint
      
      - test:
        docker:
          - image: circleci/node:13.8.0
          steps:
            - checkout
            - run npm i
            - run npm run lint

      - analyze:
        docker:
          - image: circleci/node:13.8.0
          steps:
            - checkout
            - run npm i
            - run npm run lint

workflows:
  my_workflow:
    jobs:
      - build
      - test:
        requires:
          - build
      - analyze:
        requires:
          -t est
